When aborting print message to remove the snapshot lv (if active)

diff --git a/virt-move b/virt-move
--- a/virt-move
+++ b/virt-move
@@ -65,6 +65,15 @@ if [ "$1" == "" -o "$2" == "" -o "${SHOW_HELP}" == "1" ] ; then
   exit 0
 fi
 
+cleanup() {
+  echo "* Aborting!"
+
+  if [ "$SNAPSHOT_LV" != "" ] ; then
+    echo "- Remove the snapshot logical volume: 'lvremove ${SNAPSHOT_LV}'"
+  fi
+}
+trap cleanup EXIT
+
 VM=$1
 HOST=$2
 
@@ -186,4 +195,5 @@ if [ -e $AUTOSTART_FILE ] ; then
   echo "- VM autostart configuration /etc/libvirt/qemu/autostart/${VM}.xml"
 fi
 
+trap '' EXIT
 exit $EXIT_CODE
